version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.staging
    container_name: gsuite_discord_app_staging
    restart: unless-stopped
    tty: true
    networks:
      - app-network
    ports:
      - "8999:8080"
networks:
  app-network:
    driver: bridge
