version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: gsuite_discord_app_dev
    restart: unless-stopped
    tty: true
    networks:
      - app-network
    ports:
      - "8999:8080"
    volumes:
      - "./src:/var/www/html"
networks:
  app-network:
    driver: bridge
