version: '3'

services:
  # Nginx Service
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./gsuite_discord_bot:/gsuite_discord_bot
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - /etc/localtime:/etc/localtime
    networks:
      - nginxphp

  # PHP Service
  php:
    container_name: php7.4
    build:
      context: ./docker/php
    volumes:
      - ./gsuite_discord_bot:/gsuite_discord_bot
    expose:
      - 9000
    networks:
      - nginxphp

networks:
  nginxphp: