version: '3'
services:
  app:
    build: ./docker/app
    container_name: gsuite_discord_app
    restart: unless-stopped
    tty: true
    networks:
      - app-network
    ports:
      - "8999:8080"
    volumes:
      - ".:/var/www/html"
networks:
  app-network:
    driver: bridge
