version: '3'

services:


  # PHP Service
  app:
    container_name: gsuite
    build:
      context: ./docker
    volumes:
      - ./gsuite_discord_bot/public:/var/www/localhost/htdocs
    ports:
      - "8989:80"
