version: '3'

services:
  # Nginx Service
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ../gsuite_discord_bot:/gsuite_discord_bot
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/localtime:/etc/localtime
    networks:
      - nginxphp

  # PHP Service
  php:
    container_name: php7.4
    build:
      context: ./php
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=5.7
    volumes:
      - ../gsuite_discord_bot:/gsuite_discord_bot
    expose:
      - 9000
    networks:
      - nginxphp

  database:
    build:
      context: ./database
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/mysql

  # PhpMyAdmin Service
  phpmyadmin:
    container_name: PHPMyAdmin
    image: phpmyadmin/phpmyadmin:5
    ports:
      - 8989:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - database

networks:
  nginxphp:

volumes:
  mysqldata:

