name: deploy_docker_compose
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare Dev Env
        env:
          GCLOUD_SERVICE_ACCOUNT_JSON: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_JSON }}
        run: |
          mkdir -p ./src/config/dev/service_account/ && echo "$env:GCLOUD_SERVICE_ACCOUNT_JSON" > ./src/config/dev/service_account/gcloud_service_account.json
      - name: Dev
        uses: TapTap21/docker-remote-deployment-action@v1.0
        with:
          remote_docker_host: ${{ secrets.REMOTE_DOCKER_HOST }}
          ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          stack_file_name: docker-compose.staging.yml
          args: -p gsuite_app_staging up -d --build

