version: '3'

services:
  # Nginx Service
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ../gsuite_discord_bot/public:/gsuite_discord_bot/public
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/localtime:/etc/localtime
    networks:
      - nginxphp

    # PHP Service
  php:
    container_name: php7.4
    build:
      context: ./php
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=5.7
    volumes:
      - ../gsuite_discord_bot/public:/gsuite_discord_bot/public
    expose:
      - 9000
    networks:
      - nginxphp

#  php:
#    container_name: php7.4
#    image: php:7.4-fpm-alpine3.13
#    volumes:
#      - ../gsuite_discord_bot/public:/gsuite_discord_bot/public
#    expose:
#      - 9000
#    networks:
#      - nginxphp
#  php:
#    build:
#      context: ../gsuite_discord_bot
#      target: api_platform_php
#    restart: unless-stopped
#    healthcheck:
#      interval: 10s
#      timeout: 3s
#      retries: 3
#      start_period: 30s

  # MySQL Service
#  mysql:
#    container_name: MySQL8
#    image: mysql:8
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: demo
#    volumes:
#      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
#      - mysqldata:/var/lib/mysql

  database:
    build:
      context: ./database
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/mysql

  # PhpMyAdmin Service
  phpmyadmin:
    container_name: PHPMyAdmin
    image: phpmyadmin/phpmyadmin:5
    ports:
      - 8989:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - database

networks:
  nginxphp:

volumes:
  mysqldata:

